WIP: Landing knative kafka broker 1.1 components
openshift-knative/serverless-operator pull request #1393
Opened 2022-02-08 10:57 UTC by matzew

Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

subset of #1386  (just the broker bits)

DO NOT MERGE ....

2022-02-22 16:02 UTC, matzew commented
/test 4.9-operator-e2e-aws-ocp-49

2022-02-22 22:16 UTC, matzew commented
/assign @pierDipi

2022-02-23 08:01 UTC, pierDipi requested changes

2022-02-23 08:01 UTC, pierDipi commented on knative-operator/deploy/resources/knativekafka/controller/1-eventing-kafka-controller.yaml
> +
Can we remove this CM?

2022-02-23 08:24 UTC, matzew commented on knative-operator/deploy/resources/knativekafka/controller/1-eventing-kafka-controller.yaml
> +
Oh, yeah - will do thanks

2022-02-23 08:35 UTC, matzew commented
@pierDipi I have removed the `channel` config

2022-02-23 09:05 UTC, pierDipi approved these changes
/lgtm
/approve

:ship:

2022-02-23 09:21 UTC, merged