feat: adds tekton resources for building functions
openshift-knative/serverless-operator pull request #2051
Opened 2023-04-20 21:04 UTC by lance

These resources should be installed in the cluster when Serverless is installed.

I *believe* that Tekton installed already for all OpenShift instances and so a reconciler is not necessary.

2023-04-21 10:19 UTC, dsimansk commented
Does it require OpenShift Pipelines/Tekton to be installed on the cluster already? Ohterwise adding unrecognized custom resource.

Moreover we should probably create a templated files in `templates` dir and at least make image params replaced by the values from `project.yaml`.

2023-04-21 12:28 UTC, lance commented
> Does it require OpenShift Pipelines/Tekton to be installed on the cluster already? Ohterwise adding unrecognized custom resource.

I was under the impression that pipelines are always installed on an OpenShift cluster, but I think that is wrong. I need to check to see if it is installed.

2023-04-21 13:22 UTC, cardil requested changes

2023-04-21 13:22 UTC, cardil commented on openshift-knative-operator/cmd/operator/kodata/knative-functions/1-tekton-task.yaml
Those tasks should be deployed dynamically, same as we deploy `ConsoleCliDownload` CR only if console is present. See: https://github.com/openshift-knative/serverless-operator/pull/1787

2023-04-21 19:54 UTC, lance commented
@dsimansk @cardil thanks for your feedback. I've made some changes based on your suggestions and would appreciate any additional feedback. This is my first time working with this repository, and it is a bit of black magic to me. Please point me in the right direction if I've gone astray here.

2023-04-24 10:16 UTC, skonto commented on knative-operator/cmd/manager/main.go
> +	// Check to see if Tekton is installed by looking for the pipelines CRD
I suggest we have a common logic for OCP feature discovery.
We check the cluster operator status [here](https://github.com/openshift-knative/serverless-operator/blob/main/knative-operator/cmd/manager/main.go#L176-L187) for console for example.

2023-04-26 22:28 UTC, lance commented
Closing this. After spending some time chatting with @cardil I think it may not make sense to install these resources via the operator, but instead have them be user-installed via artifacthub.io.

2023-04-26 22:28 UTC, closed without merging