updating to kn-client 0.15.2
openshift-knative/serverless-operator pull request #417
Opened 2020-08-27 07:34 UTC by rhuss

2020-08-27 14:18 UTC, rhuss commented
/retest

2020-08-27 16:08 UTC, rhuss commented
/retest

2020-08-28 05:57 UTC, rhuss commented
/retest

2020-08-28 06:18 UTC, navidshaikh requested changes

2020-08-28 06:18 UTC, navidshaikh commented on olm-catalog/serverless-operator/1.9.0/serverless-operator.v1.9.0.clusterserviceversion.yaml
> +                      value: registry.svc.ci.openshift.org/openshift/knative-v0.15.2:kn-cli-artifacts
there is another reference of this image at line no:523 in `spec.relatedImages` section which should be updated as well

2020-08-28 13:20 UTC, navidshaikh approved these changes
/retest

lgtm

2020-09-01 08:14 UTC, matzew commented
/test 4.5-upstream-e2e-aws-ocp-45

2020-09-01 11:50 UTC, markusthoemmes approved these changes
/lgtm
/approve

2020-09-01 13:18 UTC, merged