Add 4.7 channel
openshift-knative/serverless-operator pull request #766
Opened 2020-12-18 08:46 UTC by warrenvw

As suggested, add the 4.7 channel.

2020-12-19 02:09 UTC, warrenvw commented
/retest

2021-01-12 00:54 UTC, warrenvw commented
/retest

2021-01-12 15:49 UTC, markusthoemmes commented on olm-catalog/serverless-operator/project.yaml
> +      - '4.6,4.7'
This must actually be an enumerated list. This breaks the code figuring out which channel to use for the subscription, see https://github.com/openshift-knative/serverless-operator/blob/28c6716b70c438a15ae747fd6c2e3ce7ed472350/hack/lib/vars.bash#L57.

2021-01-12 20:33 UTC, warrenvw commented
/retest

2021-01-12 23:09 UTC, cardil requested changes
Nit.

2021-01-12 23:09 UTC, cardil commented on olm-catalog/serverless-operator/project.yaml
> +      - 4.7
```suggestion
      - '4.6'
      - '4.7'
```
Without quotes they will be read as floats, but they should be strings. I advised adding quotes.

2021-01-13 11:59 UTC, markusthoemmes approved these changes
/lgtm
/approve

2021-01-13 12:10 UTC, merged